name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Check for changesets and publish directly
        run: |
          # Check if there are any changesets
          if ls .changeset/*.md >/dev/null 2>&1 && [ "$(ls -1 .changeset/*.md | grep -v README.md | wc -l)" -gt 0 ]; then
            echo "Changesets found. Processing version updates and publishing..."
            
            # Update versions and generate changelog
            pnpm changeset version
            
            # Commit version updates
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "chore: release version updates [skip ci]" || exit 0
            git push
            
            # Publish to npm
            pnpm changeset publish
            echo "✅ Published to npm successfully"
          else
            echo "No changesets found. Skipping release."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
